# Numpy

In [3]:
import numpy as np

In [4]:
l = [1, 2, 3]
A=np.array(l)

In [5]:
A

array([1, 2, 3])

In [6]:
for e in l:
    print(e)


1
2
3


In [7]:
l.append(4)

In [8]:
l

[1, 2, 3, 4]

In [9]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [12]:
l = l+[5]

In [13]:
l

[1, 2, 3, 4, 5]

In [14]:
A = A+[3, 4]

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [15]:
l2 = []
for r in l:
    l2.append(r+r)

In [16]:
l2

[2, 4, 6, 8, 10]

In [17]:
A+A

array([2, 4, 6])

In [18]:
A*2

array([2, 4, 6])

In [19]:
2*l

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [20]:
l2 = []
for r in l:
    l2.append(r*r)

In [21]:
l2

[1, 4, 9, 16, 25]

In [22]:
A*2

array([2, 4, 6])

In [23]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [24]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [25]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [26]:
e = np.array([1, 2])